# Site settings

title: AED-netwerk Gemeente Duiven
description: De stichting heeft als doel het streven naar de oprichting, in stand houding en verbetering van een verfijnd AED-netwerk in de gemeente Duiven dat voldoet aan de wensen van alle inwoners.
email: info@aed-duiven.nl

baseurl: "" # the subpath of your site, e.g. /blog/
url: ""

url: "http://aed-duiven.nl" # the base hostname & protocol for your site
twitter_username: aedduiven

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['PSD', 'README.md', 'CNAME']
